### PR TITLE
Improve language around patient data access token

### PR DESCRIPTION
**Pull request by vadi2**

### CODE REVIEW

**Review by mbaltus — COMMENTED** [review]
If I understand it correctly, you do not necessarily need the 'launch/patient' scope. This is only when the app needs the context. But just the patient context + patient/x scopes already limits the output to that patient's compartment.
I do agree with the addition at the end of the sentence. That does make more clear what I was struggling with.

**Comment by vadi2** [comment]
Now I'm confused. The standard here could certainly be clearer.

@alexzautke your thoughts?

**Comment by mbaltus** [comment]
The SMART specs say: "launch/patient: When launching outside the EHR, ask for a patient to be selected at launch time".

The way I read it, is that 'launch/patient' is a scope that can be added on the standalone launch. If the app needs the context, it adds this to the scopes, but by no means it is a mandatory thing. The auth server then makes sure a patient context is added to the token, for example by showing a patient selector. It does not say anything about the FHIR server needing the 'launch/patient' in the scopes to make use of the patient context and patient/x.x scopes.
But I do not know if Vonk expects it to be there - I think it worked fine without - so perhaps @alexzautke can tell us more.

**Comment by vadi2** [comment]
What's the definition of "context"? The patient claim in the token? If that's the case then it's not really optional to request it for reading patient data, it's mandatory.

**Comment by alexzautke** [comment]
If the app requests a patient-level scope, the auth server is supposed to include a patient claim as well:

"When granting a patient-level scopes like patient/*.read, the server SHALL provide a “patient” launch context parameter." (http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html)

Meaning that @mbaltus is correct by saying that you don't need to have the "launch/patient" patient scope in the request to get the patient claim in the access token. Only if you are launching from an EHR and need to know the patient context, you can force is by requesting the scope. Same for having a user-level access scope but still the need to know the patient context.

**Comment by alexzautke** [comment]
I think we need to make this differentiation in our documentation as well

**Comment by alexzautke** [comment]
@mbaltus @vadi2 I've updated the PR a bit, could you check if this is now clear?

**Comment by vadi2** [comment]
Yep I think that's a good way of doing it.

**Review by alexzautke — APPROVED** [review]

**Pull request merged**
